name: Feedstock CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    - cron: "17 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  bookshelf:
    name: Bookshelf
    uses: climate-resource/copier-bookshelf-dataset/.github/workflows/feedstock-ci.yaml@v0.6.0
    with:
      recipes: >-
        bookshelf.yaml
      main-ref: main
      api-base-url: ${{ vars.BOOKSHELF_API_URL }}
      sdk-version: "1.0.0"

  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - run: uv sync --locked
      - run: uv run pytest -q
